kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  CHECK_INTERVAL: {{ required "checkInterval is required" .Values.env.checkInterval | quote }}
  {{- with .Values.metrics.port}}
  METRIC_PORT: {{ . | quote }}
  {{- end}}
  {{- with .Values.metrics.ip}}
  METRIC_IP: {{ . | quote }}
  {{- end}}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  {{- with .Values.env.sentryDns}}
  SENTRY_DSN: {{ . | quote }}
  {{- end}}