kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  SERVER.HOST: {{ required "server host is required" .Values.application.server.host | quote }}
  SERVER.PORT: {{ required "server port is required" .Values.application.server.port | quote }}
  S3.HOST: {{ required "S3 host is required" .Values.application.s3.host | quote }}
  S3.REGION: {{ required "S3 region is required" .Values.application.s3.region | quote }}
  BUCKET.ENTRIES: {{ include "config.entries" . }}
  LOG_LEVEL: {{ .Values.application.logLevel | quote }}
  {{- with .Values.application.sentryDsn}}
  SENTRY_DSN: {{ . | quote }}
  {{- end}}


{{/*
Convert entriy values to the correct format
Example: key:bucket,file.txt; key2:bucket2,config.yaml
*/}}
{{- define "config.entries" -}}
{{- $list := list -}}
{{- range $k, $v := .Values.application.handler.entries -}}
{{- $list = append $list (printf "%s:%s" $k (join "," $v)) -}}
{{- end -}}
{{ join "; " $list }}
{{- end -}}