{{- if and (not .Values.application.s3.secretName) .Values.application.s3.accessKey .Values.application.s3.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  access_key: {{ .Values.application.s3.accessKey | quote }}
  secret_key: {{ .Values.application.s3.secretKey | quote }}
{{- end }}
