application:
  handler:
    entries:
      4tv#Sjfpj&:
        - bucket,file.txt
  s3:
    accessKey: "fe47359d4fe04df0a8689fba2358c8d2.access"
    secretKey: "7ae0f15050f34f29b394495331ca28a2"
    host: "s3.amazon.com"
    region: "eu-central-1"

ingress:
  enabled: false