application:
  handler:
    entries:
      4tv#Sjfpj&:
        - bucket,file.txt
      hGEvxxML5*:
        - bucket2,dir/file.txt

  s3:
    accessKey: "fe47359d4fe04df0a8689fba2358c8d2.access"
    secretKey: "7ae0f15050f34f29b394495331ca28a2"
    host: "s3.amazon.com"
    region: "eu-central-1"

ingress:
  enabled: true
  hosts:
    - test.test.de
  tls:
    - secretName: test-tls
      hosts:
        - test.test.de