name: 'Setup Helm Environment'
description: 'Installs Helm and common plugins'
inputs:
  token:
    description: 'GitHub Token'
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Install Helm
      uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
      with:
        version: 'latest'

    - name: Install helm-unittest
      shell: bash
      run: |
        helm plugin install https://github.com/helm-unittest/helm-unittest --verify=false

    - name: Install helm-schema
      shell: bash
      run: |
        helm plugin install https://github.com/dadav/helm-schema --verify=false
