application:
  handler:
    targetBase: "https://test.google.com"
    paths:
      api/webhook:
        - ALL

  cloudflareAccess:
    clientId: "testId"
    clientSecret: "testSecret"

ingress:
  enabled: false